services:
  nginx:
    image: nginx:1-alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html  # Optional: for direct static file serving
    depends_on:
      - web
    networks:
      - app_network

  web:
    build: ./apache-php      
    container_name: apache_php
    # Remove external port mapping - Nginx will handle it
    expose:
      - "80"
    volumes:
      - ./html:/var/www/html
      - ./xdebug-profiler:/var/log/xdebug-profiler
    extra_hosts:
      - "host.docker.internal:host-gateway"        
    depends_on:
      - db
    networks:
      - app_network
      
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: receipt_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_PORT=6379
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass admin
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:    